#+OPTIONS: html-postamble:nil
#+OPTIONS: toc:nil
#+OPTIONS: title:nil
#+OPTIONS: num:nil
#+OPTIONS: ::800
#+OPTIONS: html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+STARTUP:    showall
#+TITLE:      Free Bread
#+AUTHOR:     Adam Massmann
#+EMAIL:      massma "at" autistici "dot" org
#+LANGUAGE:   en

[[file:index.org][{Back to Home}]]

*** Free Bread

With the indispensable help of friends and the internet, I've
developed a bread recipe. The recipe evolved to be easy to make and
versatile. However ease and versatility came at a cost: this probably
won't be the most airy, delicious bread you've ever had.

The recipe is provided below. If you have any questions about it, or
suggestions for improvement, please email me.

I can bake and deliver this bread anywhere in Manhattan between 110th
and 155th streets. If you would like some bread, please send an email
to massma "at" autistici "dot" org, with the following information:

- Delivery address
- Whether you would like baked bread or dough. I recommend dough, as
  the bread is best fresh out of the oven. If you pick dough, see the
  recipe for baking instructions.
- If you would like baked bread:
  - Whether you would prefer more of a "mini-loaf/roll" type bread, or
    a flatbread (I prefer flatbread).
  - What toppings, if any, you would like. Current choices are:
    - Nutritional yeast
    - Smoked Paprika
    - Za'atar
    - Garlic Powder
    - Fresh Garlic

I'll respond with an estimated time of delivery. Sometimes I'm away
from the internet, and it may take me a bit to respond.

**** Sourdough Multipurpose Bread Recipe
***** Ingredients
- 3 cups wheat flour

- 2 teaspoons salt

- 1 cup sourdough starter (if you need starter, let me know and I
  can deliver some)

- 2 cups water

- Whatever topping/seasonings you want. Some ideas:
  - Chutneys
  - Smoked paprika and nutritional yeast
  - Za'atar

***** Instructions
1. In a large bowl, mix together the flour and salt.

2. Add the starter and water, and mix until the flour is fully mixed
   in with the wet ingredients.

3. Makes ~6 flatbreads/rolls. I usually split the dough into 6 equal
   portions and store in separate (small-ish) containers. Line
   containers(s) with oil, and pour dough in. Will keep in fridge
   mostly indefinitely (with varying sourness, airy-ness, etc.).

4. When you want to bake, spread on a greased skillet or baking sheet,
   top with seasonings (we like smoky/spicy, with some pickled things
   or garlic pressed into the dough), and bake for 15-20 min at 430F
   (could vary depending on oven; we go until the bottom is crispy but
   not burnt). Can spread thin for more of a flat bread, or just
   puddle in in the middle for more of a loaf-type bread.

***** Notes
- For a different flavor/nutritional profile you can substitute up to
  1/2 cup of the wheat flour with non-wheat flour (for example,
  chickpea flour).
